---
kind: Template
apiVersion: v1
metadata:
  name: "${NAME}-deployment-template"
  creationTimestamp: 
objects:

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
    annotations:
      description: Defines how to deploy ${NAME}
  spec:
    strategy:
      type: Rolling
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${NAME}"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: "${SOURCE_IMAGE_NAME}:${TAG_NAME}"
    replicas: 1
    selector:
      name: "${NAME}"
    template:
      metadata:
        name: "${NAME}"
        labels:
          name: ${NAME}
          app: ${APP_GROUP}
          app-group: ${APP_GROUP}
      spec:
        containers:
        - name: "${NAME}"
          image: ''
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: NODE_ENV
            value: production
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: bctw
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: bctw
          - name: BCTW_IS_LIVE_DATA
            value: 'true'
          - name: BCTW_SESSION_SALT
            value: qrjewvcu78ds97f234523jkldvjdjdsl
          - name: BASE_URL
            value: /
          - name: DEV_MODE
            value: 'true'
          - name: POSTGRES_SERVER_HOST
            value: bctw-db.dgsbmb-dev.svc.cluster.local
          - name: POSTGRES_SERVER_PORT
            value: '5432'
          - name: POSTGRES_DB
            value: bctw

- kind: Service
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
    annotations:
      description: Exposes and load balances the application pods.
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      name: "${NAME}"
    type: ClusterIP
    sessionAffinity: None

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
    name: "${NAME}"
  spec:
    host: "${APPLICATION_DOMAIN}"
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: "${NAME}"
      weight: 100

- kind: HorizontalPodAutoscaler
  apiVersion: autoscaling/v1
  metadata:
    name: "${NAME}"
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
  spec:
    scaleTargetRef:
      kind: DeploymentConfig
      name: "${NAME}"
    minReplicas: 1
    maxReplicas: 2

parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: bctw-ui
- name: APP_GROUP
  displayName: App Group
  description: Used to group components together.
  required: true
  value: bctw
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  description: The name of the image to use for this resource.
  required: true
  value: bctw-ui 
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  description: The namespace of the OpenShift project containing the imagestream for the application.
  required: true
  value: dgsbmb-tools
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: dev
- name: APPLICATION_DOMAIN
  description: The exposed hostname that will route to the service, e.g., myappname.pathfinder.gov.bc.ca, if left blank a value will be defaulted.
  displayName: Application Domain
  value: bctw-ui-dgsbmb-dev.pathfinder.gov.bc.ca
- name: CPU_REQUEST
  displayName: CPU Request
  description: Starting amount of CPU the container can use.
  value: 10m
- name: CPU_LIMIT
  displayName: CPU Limit
  description: Maximum amount of CPU the container can use.
  value: 500m
- name: MEMORY_REQUEST
  displayName: Memory Request
  description: Starting amount of memory the container can use.
  value: 10Mi
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  value: 512Mi